source 'http://rubygems.org'

gem 'rails', '2.3.11'
gem 'sqlite3', '>=1.3.4'
gem "erector", :path => "../../.."
gem "i18n"
gem "rdoc", "~>3.8"

group :test do
  gem 'rspec'
  gem 'rr'
  gem 'nokogiri'
  gem "wrong", ">=0.5.4"
end
