source 'http://rubygems.org'

gem 'rails', '2.3.11'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "erector", :path => "../../.."
gem "i18n"

group :test do
  gem 'rspec'
  gem 'rr'
  gem 'nokogiri'
  gem "wrong", ">=0.5.4"
end
