# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'
require "rspec/core/rake_task"


RSpec::Core::RakeTask.new(:rails2) do |spec|
  spec.pattern = 'spec/*_spec.rb'
  spec.rspec_opts = ['--backtrace']
  # spec.skip_bundler = true
  # spec.gemfile = 'spec/rails2/rails_app/Gemfile'
end
