dir = File.dirname(__FILE__)
require "action_controller"
require "#{dir}/rails/rails_version"
require "#{dir}/rails/rails_form_builder"
require "#{dir}/rails/extensions/rails_widget"
require "#{dir}/rails/extensions/action_controller"
require "#{dir}/rails/extensions/action_view"
require "#{dir}/rails/extensions/rails_widget/rails_helpers"
require "#{dir}/rails/template_handlers/rb_handler"
require "#{dir}/rails/template_handlers/ert_handler"
