require "erector/widgets/environment_badge"
require "erector/widgets/field_table"
require "erector/widgets/form"
require "erector/widgets/external_renderer"
require "erector/widgets/page"
require "erector/widgets/table"
